import express from 'express';
import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { z } from 'zod';
import { env } from '@ikonetu/config';
import { db } from '@ikonetu/database';
import {
  requestId, rateLimiter, authenticate,
  validate, errorHandler, NotFoundError, AppError,
} from '@ikonetu/shared/middleware';

const app = express();
app.use(express.json());
app.use(requestId);

// ════════════════════════════════════════════════════════════
// REPORT SERVICE — port 3018  (R09 revenue stream)
// Generates downloadable PDF and Excel reports:
//
//  R09-1: Founder Score Report (PDF)      — £40 per report
//  R09-2: Lender Portfolio Report (Excel) — £120/month
//  R09-3: Investor Pipeline Report (PDF)  — £80 per report
//  R09-4: Platform Intelligence (Excel)   — £800/quarter (admin)
//
// Pricing enforced at billing-service level via credit deduction.
// Report service only generates — billing service gates access.
// ════════════════════════════════════════════════════════════

const IKONETU_GOLD  = '#C9900C';
const IKONETU_BLACK = '#0A0A0A';
const TIER_COLORS = {
  EARLY: '#94A3B8', RISING: '#F59E0B', INVESTABLE: '#10B981', ELITE: '#C9900C',
};

// ── Shared helpers ────────────────────────────────────────────

function formatDate(d: Date | string): string {
  return new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

function formatScore(n: number): string {
  return n.toString().padStart(4, ' ');
}

// ════════════════════════════════════════════════════════════
// R09-1: FOUNDER SCORE REPORT — PDF
// ════════════════════════════════════════════════════════════

async function buildFounderScorePDF(
  ventureId: string,
  doc: PDFKit.PDFDocument
): Promise<void> {

  const venture = await db('ventures').where({ id: ventureId }).first();
  if (!venture) throw new NotFoundError('Venture');

  const score = await db('scores').where({ venture_id: ventureId, is_current: true }).first();
  const breakdowns = score ? await db('score_breakdowns').where({ score_id: score.id }).orderBy('weighted_score', 'desc') : [];
  const history = await db('score_history').where({ venture_id: ventureId }).orderBy('snapshot_date', 'asc').limit(12);
  const documents = await db('venture_documents').where({ venture_id: ventureId }).whereNull('deleted_at');
  const bankability = await db('bankability_scores').where({ venture_id: ventureId }).orderBy('scored_at', 'desc').first();

  const tier = score?.tier ?? 'EARLY';
  const tierLabels: Record<string, string> = {
    EARLY: 'Early Stage', RISING: 'Rising', INVESTABLE: 'Investable', ELITE: 'Elite',
  };

  // ── Page 1: Cover ────────────────────────────────────────
  doc.rect(0, 0, doc.page.width, 200).fill(IKONETU_BLACK);

  doc.fillColor('#F5C842').fontSize(28).font('Helvetica-Bold')
    .text('IkonetU', 50, 40);
  doc.fillColor('#888888').fontSize(11).font('Helvetica')
    .text('African Founder Scoring Platform', 50, 75);

  doc.fillColor('#FFFFFF').fontSize(22).font('Helvetica-Bold')
    .text('Founder Score Report', 50, 110);
  doc.fillColor('#AAAAAA').fontSize(12).font('Helvetica')
    .text(`${venture.name}`, 50, 140)
    .text(`Generated: ${formatDate(new Date())}`, 50, 160);

  // Score badge
  const badgeX = doc.page.width - 170;
  doc.roundedRect(badgeX, 60, 120, 120, 8).fill(TIER_COLORS[tier] + '30');
  doc.fillColor(TIER_COLORS[tier]).fontSize(48).font('Helvetica-Bold')
    .text(String(score?.total_score ?? 0), badgeX + 10, 80, { width: 100, align: 'center' });
  doc.fontSize(11)
    .text(tierLabels[tier], badgeX + 10, 130, { width: 100, align: 'center' });
  doc.fillColor('#AAAAAA').fontSize(9)
    .text('out of 1000', badgeX + 10, 148, { width: 100, align: 'center' });

  doc.fillColor(IKONETU_BLACK);

  // Disclaimer
  doc.y = 220;
  doc.rect(50, doc.y, doc.page.width - 100, 44).fill('#F8F7F4');
  doc.fillColor('#555555').fontSize(9).font('Helvetica')
    .text(
      'IMPORTANT: This report is generated by IkonetU Technology Limited for informational purposes only. ' +
      'It does not constitute financial advice, a credit assessment, or an investment recommendation. ' +
      'IkonetU scores reflect data available at the time of calculation and may not be current.',
      58, doc.y + 8, { width: doc.page.width - 116 }
    );

  // ── Page 1 continued: Summary ────────────────────────────
  doc.y = 290;
  doc.fillColor(IKONETU_BLACK).fontSize(14).font('Helvetica-Bold').text('Score Summary', 50, doc.y);
  doc.y += 24;

  const summaryItems = [
    ['Venture',           venture.name],
    ['Sector',            venture.sector || '—'],
    ['Country',           venture.country || '—'],
    ['Stage',             venture.stage || '—'],
    ['IkonetU Score',     score ? `${score.total_score} / 1000` : 'Not yet calculated'],
    ['Tier',              tierLabels[tier]],
    ['Confidence',        score ? `${Math.round(score.confidence_pct)}%` : '—'],
    ['Bankability Score', bankability ? `${Math.round(bankability.total_score)} / 100` : '—'],
    ['Report Date',       formatDate(new Date())],
    ['Calculated',        score ? formatDate(score.scored_at) : '—'],
  ];

  for (const [label, value] of summaryItems) {
    doc.rect(50, doc.y, doc.page.width - 100, 22).fill(summaryItems.indexOf([label, value]) % 2 === 0 ? '#FFFFFF' : '#F8F7F4');
    doc.fillColor('#888888').fontSize(10).font('Helvetica').text(label, 56, doc.y + 6, { width: 150 });
    doc.fillColor(IKONETU_BLACK).font('Helvetica-Bold').text(String(value), 210, doc.y + 6, { width: 300 });
    doc.y += 22;
  }

  // ── Page 2: Category breakdown ───────────────────────────
  doc.addPage();

  doc.fillColor(IKONETU_BLACK).fontSize(14).font('Helvetica-Bold').text('Score Breakdown by Category', 50, 50);
  doc.fontSize(10).font('Helvetica').fillColor('#888888')
    .text('Higher verification tier signals produce greater score impact. Self-declared data (Tier 4) contributes 60% of a signal\'s raw value; government-verified data (Tier 1) contributes 100%.', 50, 72, { width: doc.page.width - 100 });

  doc.y = 110;

  // Category bars
  for (const b of breakdowns) {
    const pct = b.max_possible > 0 ? (b.weighted_score / b.max_possible) : 0;
    const barWidth = (doc.page.width - 200) * pct;

    doc.fillColor(IKONETU_BLACK).fontSize(11).font('Helvetica-Bold')
      .text(b.category.charAt(0).toUpperCase() + b.category.slice(1), 50, doc.y);

    doc.fillColor('#888888').fontSize(9).font('Helvetica')
      .text(`${Math.round(b.weighted_score)} / ${b.max_possible} points  ·  ${b.signals_found} signals  ·  ${b.signals_verified} verified`, 200, doc.y + 2);

    doc.y += 18;

    // Track background
    doc.rect(50, doc.y, doc.page.width - 200, 10).fill('#E8E6E0');
    // Fill
    if (barWidth > 0) {
      doc.rect(50, doc.y, barWidth, 10).fill(
        pct >= 0.8 ? '#10B981' : pct >= 0.5 ? '#F59E0B' : '#94A3B8'
      );
    }
    // Percentage label
    doc.fillColor('#555555').fontSize(9).font('Helvetica')
      .text(`${Math.round(pct * 100)}%`, doc.page.width - 140, doc.y);

    doc.y += 22;
  }

  // ── Page 3: Score history chart (text-based) ─────────────
  if (history.length > 0) {
    doc.addPage();
    doc.fillColor(IKONETU_BLACK).fontSize(14).font('Helvetica-Bold').text('Score Progression', 50, 50);

    doc.y = 80;
    doc.rect(50, doc.y, doc.page.width - 100, 24).fill('#F8F7F4');
    doc.fillColor('#888888').fontSize(9).font('Helvetica').text('Date', 56, doc.y + 8, { width: 100 });
    doc.text('Score', 160, doc.y + 8, { width: 60 });
    doc.text('Tier', 230, doc.y + 8, { width: 100 });
    doc.text('Change', 340, doc.y + 8, { width: 80 });
    doc.y += 24;

    for (let i = 0; i < history.length; i++) {
      const h = history[i];
      const prev = history[i - 1];
      const change = prev ? h.total_score - prev.total_score : null;

      doc.rect(50, doc.y, doc.page.width - 100, 20).fill(i % 2 === 0 ? '#FFFFFF' : '#F8F7F4');
      doc.fillColor('#555555').fontSize(9).font('Helvetica').text(formatDate(h.snapshot_date), 56, doc.y + 5, { width: 100 });
      doc.fillColor(IKONETU_BLACK).font('Helvetica-Bold').text(String(h.total_score), 160, doc.y + 5, { width: 60 });
      doc.fillColor(TIER_COLORS[h.tier as keyof typeof TIER_COLORS] || '#888888').font('Helvetica').text(h.tier, 230, doc.y + 5, { width: 100 });
      if (change !== null) {
        doc.fillColor(change > 0 ? '#10B981' : change < 0 ? '#EF4444' : '#888888')
          .text(`${change > 0 ? '+' : ''}${change}`, 340, doc.y + 5, { width: 80 });
      }
      doc.y += 20;
    }
  }

  // ── Page 4: Documents verified ───────────────────────────
  if (documents.length > 0) {
    doc.addPage();
    doc.fillColor(IKONETU_BLACK).fontSize(14).font('Helvetica-Bold').text('Verification Evidence', 50, 50);

    doc.y = 80;
    for (const d of documents) {
      const verified = d.verified;
      doc.rect(50, doc.y, doc.page.width - 100, 22).fill(verified ? '#ECFDF5' : '#F8F7F4');
      doc.fillColor(verified ? '#065F46' : '#888888').fontSize(10)
        .text(verified ? '✓' : '○', 56, doc.y + 6, { width: 20 });
      doc.fillColor(IKONETU_BLACK).font('Helvetica')
        .text(d.document_type.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()), 80, doc.y + 6, { width: 200 });
      if (verified) {
        doc.fillColor('#888888').fontSize(9)
          .text(`Tier ${d.verification_tier} · ${formatDate(d.verified_at)}`, 290, doc.y + 7, { width: 200 });
      } else {
        doc.fillColor('#AAAAAA').fontSize(9).text('Pending verification', 290, doc.y + 7);
      }
      doc.y += 22;
    }
  }

  // ── Footer on all pages ──────────────────────────────────
  const pageCount = doc.bufferedPageRange();
  for (let i = pageCount.start; i < pageCount.start + pageCount.count; i++) {
    doc.switchToPage(i);
    doc.rect(0, doc.page.height - 36, doc.page.width, 36).fill('#F8F7F4');
    doc.fillColor('#AAAAAA').fontSize(8).font('Helvetica')
      .text(
        `IkonetU Technology Limited · Registered in England and Wales · customer.service@ikonetu.com · Page ${i + 1} of ${pageCount.count}`,
        50, doc.page.height - 24, { align: 'center', width: doc.page.width - 100 }
      );
  }
}

// ════════════════════════════════════════════════════════════
// R09-2: LENDER PORTFOLIO REPORT — Excel
// ════════════════════════════════════════════════════════════

async function buildLenderPortfolioExcel(
  lenderId: string,
  workbook: ExcelJS.Workbook
): Promise<void> {

  const lenderProfile = await db('lender_profiles').where({ id: lenderId }).first();
  if (!lenderProfile) throw new NotFoundError('Lender profile');

  const portfolio = await db('lender_portfolios as lp')
    .join('ventures as v', 'lp.venture_id', 'v.id')
    .join('users as u', 'v.user_id', 'u.id')
    .leftJoin('scores as s', function () {
      this.on('s.venture_id', 'v.id').andOn(db.raw('s.is_current = true'));
    })
    .leftJoin('bankability_scores as b', function () {
      this.on('b.venture_id', 'v.id');
    })
    .where({ 'lp.lender_id': lenderId })
    .select(
      'v.name', 'v.sector', 'v.country', 'v.stage',
      's.total_score', 's.tier', 's.confidence_pct', 's.scored_at',
      'b.total_score as bankability',
      'lp.status', 'lp.disbursed_amount', 'lp.disbursed_currency', 'lp.disbursed_at',
      'lp.monitoring_active',
    )
    .orderBy('s.total_score', 'desc');

  // Sheet 1: Portfolio Overview
  const sheet1 = workbook.addWorksheet('Portfolio Overview');
  sheet1.columns = [
    { header: 'Venture',          key: 'name',             width: 28 },
    { header: 'Sector',           key: 'sector',           width: 18 },
    { header: 'Country',          key: 'country',          width: 10 },
    { header: 'Stage',            key: 'stage',            width: 12 },
    { header: 'IkonetU Score',    key: 'total_score',      width: 14 },
    { header: 'Tier',             key: 'tier',             width: 12 },
    { header: 'Confidence %',     key: 'confidence_pct',   width: 14 },
    { header: 'Bankability Score',key: 'bankability',      width: 16 },
    { header: 'Status',           key: 'status',           width: 14 },
    { header: 'Disbursed',        key: 'disbursed_amount', width: 14 },
    { header: 'Currency',         key: 'disbursed_currency', width: 10 },
    { header: 'Disbursed Date',   key: 'disbursed_at',     width: 16 },
    { header: 'Score Date',       key: 'scored_at',        width: 16 },
    { header: 'Monitoring',       key: 'monitoring_active', width: 12 },
  ];

  // Style header row
  sheet1.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  sheet1.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0A0A0A' } };
  sheet1.getRow(1).height = 20;

  for (const row of portfolio) {
    const excelRow = sheet1.addRow({
      ...row,
      total_score:      row.total_score ?? '—',
      confidence_pct:   row.confidence_pct ? `${Math.round(row.confidence_pct)}%` : '—',
      bankability:      row.bankability ? Math.round(row.bankability) : '—',
      disbursed_amount: row.disbursed_amount ?? '—',
      disbursed_at:     row.disbursed_at ? formatDate(row.disbursed_at) : '—',
      scored_at:        row.scored_at ? formatDate(row.scored_at) : '—',
      monitoring_active: row.monitoring_active ? 'Yes' : 'No',
    });

    // Colour-code tier column
    const tierCell = excelRow.getCell('tier');
    const colors: Record<string, string> = {
      EARLY: 'FF94A3B8', RISING: 'FFF59E0B', INVESTABLE: 'FF10B981', ELITE: 'FFC9900C',
    };
    if (row.tier && colors[row.tier]) {
      tierCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: colors[row.tier] } };
      tierCell.font = { color: { argb: 'FFFFFFFF' }, bold: true };
    }
  }

  // Auto-filter
  sheet1.autoFilter = { from: 'A1', to: 'N1' };
  sheet1.freezeRows(1);

  // Sheet 2: Score History
  const sheet2 = workbook.addWorksheet('Score History');
  sheet2.columns = [
    { header: 'Venture',    key: 'venture',   width: 28 },
    { header: 'Date',       key: 'date',      width: 16 },
    { header: 'Score',      key: 'score',     width: 10 },
    { header: 'Tier',       key: 'tier',      width: 12 },
    { header: 'Confidence', key: 'confidence', width: 12 },
  ];

  sheet2.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  sheet2.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0A0A0A' } };

  for (const p of portfolio) {
    const history = await db('score_history').where({ venture_id: p.name }).orderBy('snapshot_date');
    for (const h of history) {
      sheet2.addRow({
        venture:    p.name,
        date:       formatDate(h.snapshot_date),
        score:      h.total_score,
        tier:       h.tier,
        confidence: `${Math.round(h.confidence_pct)}%`,
      });
    }
  }

  sheet2.autoFilter = { from: 'A1', to: 'E1' };
  sheet2.freezeRows(1);

  // Sheet 3: Summary stats
  const sheet3 = workbook.addWorksheet('Summary');
  sheet3.getColumn(1).width = 30;
  sheet3.getColumn(2).width = 20;

  const statsData = [
    ['Report Generated', formatDate(new Date())],
    ['Portfolio Size', portfolio.length],
    ['Active Loans', portfolio.filter(p => p.status === 'active_loan').length],
    ['Monitoring Only', portfolio.filter(p => p.status === 'monitoring').length],
    ['Avg IkonetU Score', portfolio.length > 0 ? Math.round(portfolio.reduce((s, p) => s + (p.total_score || 0), 0) / portfolio.length) : '—'],
    ['Avg Bankability', portfolio.filter(p => p.bankability).length > 0 ? Math.round(portfolio.reduce((s, p) => s + (p.bankability || 0), 0) / portfolio.filter(p => p.bankability).length) : '—'],
    ['Tier ELITE',      portfolio.filter(p => p.tier === 'ELITE').length],
    ['Tier INVESTABLE', portfolio.filter(p => p.tier === 'INVESTABLE').length],
    ['Tier RISING',     portfolio.filter(p => p.tier === 'RISING').length],
    ['Tier EARLY',      portfolio.filter(p => p.tier === 'EARLY').length],
  ];

  for (const [label, value] of statsData) {
    const row = sheet3.addRow([label, value]);
    row.getCell(1).font = { bold: true };
  }
}

// ════════════════════════════════════════════════════════════
// ROUTES
// ════════════════════════════════════════════════════════════

// POST /api/v1/reports/founder-score/:venture_id (PDF)
app.post(
  '/api/v1/reports/founder-score/:venture_id',
  rateLimiter({ max: 10 }),
  authenticate,
  async (req, res, next) => {
    try {
      const { venture_id } = req.params;

      // Verify ownership
      const venture = await db('ventures').where({ id: venture_id }).first();
      if (!venture) throw new NotFoundError('Venture');

      const isOwner = venture.user_id === req.user!.id;
      const isAdmin = req.user!.role === 'super_admin';
      if (!isOwner && !isAdmin) throw new AppError('Access denied', 403, 'forbidden');

      // Deduct R09 credit (billing-service handles this — here we just log it)
      await db('revenue_events').insert({
        stream_id: 'R09',
        user_id: req.user!.id,
        amount: 40,
        currency: 'GBP',
        event_type: 'report.founder_score.generated',
        metadata: JSON.stringify({ ventureId: venture_id }),
      });

      // Build PDF
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        bufferPages: true,
        info: {
          Title: `IkonetU Score Report — ${venture.name}`,
          Author: 'IkonetU Technology Limited',
          Creator: 'IkonetU Report Service',
        },
      });

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="ikonetu-score-report-${venture_id}.pdf"`);
      doc.pipe(res);

      await buildFounderScorePDF(venture_id, doc);
      doc.end();
    } catch (err) { next(err); }
  }
);

// POST /api/v1/reports/lender-portfolio (Excel)
app.post(
  '/api/v1/reports/lender-portfolio',
  rateLimiter({ max: 5 }),
  authenticate,
  async (req, res, next) => {
    try {
      if (req.user!.role !== 'lender' && req.user!.role !== 'super_admin') {
        throw new AppError('Lender role required', 403, 'forbidden');
      }

      const lenderProfile = await db('lender_profiles').where({ user_id: req.user!.id }).first();
      if (!lenderProfile && req.user!.role !== 'super_admin') {
        throw new AppError('Complete your lender profile first', 400, 'no-profile');
      }

      const targetLenderId = req.body.lenderId || lenderProfile?.id;

      await db('revenue_events').insert({
        stream_id: 'R09',
        user_id: req.user!.id,
        amount: 120,
        currency: 'GBP',
        event_type: 'report.lender_portfolio.generated',
        metadata: JSON.stringify({ lenderId: targetLenderId }),
      });

      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'IkonetU Technology Limited';
      workbook.created = new Date();
      workbook.properties.date1904 = false;

      await buildLenderPortfolioExcel(targetLenderId, workbook);

      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="ikonetu-portfolio-${new Date().toISOString().slice(0,10)}.xlsx"`);

      await workbook.xlsx.write(res);
      res.end();
    } catch (err) { next(err); }
  }
);

// GET /api/v1/reports/available — what reports can this user generate
app.get(
  '/api/v1/reports/available',
  rateLimiter(),
  authenticate,
  async (req, res, next) => {
    try {
      const reports: { id: string; name: string; format: string; price: number; currency: string }[] = [];

      if (['founder', 'super_admin'].includes(req.user!.role)) {
        reports.push({
          id: 'founder-score', name: 'Founder Score Report', format: 'PDF',
          price: 40, currency: 'GBP',
        });
      }

      if (['lender', 'super_admin'].includes(req.user!.role)) {
        reports.push({
          id: 'lender-portfolio', name: 'Portfolio Monitoring Report', format: 'Excel',
          price: 120, currency: 'GBP',
        });
      }

      if (['investor', 'super_admin'].includes(req.user!.role)) {
        reports.push({
          id: 'investor-pipeline', name: 'Investor Pipeline Report', format: 'PDF',
          price: 80, currency: 'GBP',
        });
      }

      if (req.user!.role === 'super_admin') {
        reports.push({
          id: 'platform-intelligence', name: 'Platform Intelligence Report', format: 'Excel',
          price: 800, currency: 'GBP',
        });
      }

      res.json({ reports });
    } catch (err) { next(err); }
  }
);

app.get('/health', (_, res) => res.json({
  service: 'report-service', status: 'ok', version: '1.0.0',
  reports: ['founder-score (PDF)', 'lender-portfolio (Excel)', 'investor-pipeline (PDF)', 'platform-intelligence (Excel)'],
  revenueStream: 'R09',
  timestamp: new Date().toISOString(),
}));

app.use(errorHandler);

const PORT = parseInt(env.PORT) + 17; // 3018
async function start() {
  env.NODE_ENV;
  app.listen(PORT, () => {
    console.log(`✅ report-service running on port ${PORT}`);
    console.log(`   Revenue stream: R09`);
    console.log(`   Formats: PDF (pdfkit) + Excel (exceljs)`);
  });
}
start().catch((err) => { console.error(err); process.exit(1); });

export default app;
